hash-format = "sha256"

[[files]]
file = ".onedev-buildspec.yml"
hash = "dd65a5d76852cc29216ef9f69ad07e20016fad10d4de1dc6053640f2b4051404"

[[files]]
file = "config/paxi/datapacks/ibo.pw.toml"
hash = "2ec1d9560f83330a711d84f09b86a867019a6aee042aa08b22e70d04705ee4cd"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-better-desert-temples-compat.pw.toml"
hash = "e3fd385d993c8f111032e44e500e592eaf0f8dbfc9e06bbbc190c051e79e9992"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-better-dungeons-compat.pw.toml"
hash = "e793ae0523bcaf73507916657cb9b6a10eef2f8f0fbbdfcbf1f15dcc98854652"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-better-jungle-temples.pw.toml"
hash = "7a86d7c42edf9e0743e5c7c75c7c387db8830b1730ee35e837092a41241047bc"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-better-nether-fortress-compat.pw.toml"
hash = "1ab9b5df09437a3654d61d7c51c2120976970af2bc47143e2444e95c8eb295de"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-better-ocean-monuments-compat.pw.toml"
hash = "663c417eb047c14123b1f73929d30d48e539c69965acca628ecdb93581570a26"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-better-strongholds-compat.pw.toml"
hash = "f3cf02fee40c9409c950b2f6056d7efa1f552d511dae2960225c16ea02aba560"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-better-witch-huts-compat.pw.toml"
hash = "47b3c66cbe4a72fe88ccbbd6ee31ce2aac331db487c899c6b494878c96833914"
metafile = true

[[files]]
file = "config/paxi/datapacks/repurposed-structures-farmers-delight-compat.pw.toml"
hash = "2271ae5c97d5579243411cc3269acd76cf78e807ff6f9f00e20440bcae8042db"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/create-darkmode.pw.toml"
hash = "9730e890d29a8549c887b8a3de6971d272539ab540055008725d1369a483ab1d"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/create-easy-villagers-textures.pw.toml"
hash = "0f6dc55453e2132fa0c99b6ee856263db3b0dca3e8a915d1f0a8f7caabe0b428"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/create-new-age-retexture.pw.toml"
hash = "b2e5b1071dc6920ee3a99d94fd20e1c6b1e94d50dd506ebebb69cc6d2eb6568e"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/create-storage.pw.toml"
hash = "1be3bbc5b5406e0d1f3810c120630e8e2ad5c9bcb766666dc0e7f773b914a7fc"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/default-dark-mode.pw.toml"
hash = "dfa12dd42116d5fd064ae312d68e2671ec5661d2a27dc8b4f28f257bfc1ae0d2"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true

[[files]]
file = "config/squarry.cfg"
hash = "f0ae3d70cfffe99d50c13bdf085821e192419c3c1dfdd61f53d2d5f14d3ce694"

[[files]]
file = "config/viner-common.toml"
hash = "311c16ae74c603cf185d42e4701316bc2e534ffa25d3fb121293da19be3d2bd0"

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "e1a222c5ace6d1b4bab067b1245e460179a153f1e7bc8538335056fa8442155c"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1b31cb793a692d9f692b233eab37e6fed156f7b05c4a2080a75ea6c06c38c178"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "126db1f1ec01bbc4cf3393e087363e2fdbfe4a3face897ed27985b14a1a519a9"
metafile = true

[[files]]
file = "mods/bobby-reforged.pw.toml"
hash = "2a332a8963ab384a27f5257d38f9b78ad6d94f591dfd2eb14439d43abd5685da"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "15f70ccb7c7b0ff27ec791788d24de00fc6f6715311644b0fe374f006c9f230e"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "a388f4afe890e268a739cf598b68859ca3d86506a3fa3e46c17e4aa63debd309"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "a613f5d2df911fea606968bbdb56eebfd05ac02ada846cf0d2e56e72345d9338"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "5fe1f778e66001230e37dba27caf42a5a5170b9030a09c17c88c2198438695e6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "d47260d085f9c59609bbc7582968e60f4c476d934c815142360bbcc4b5113a4d"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "408ce5619020064fc084d150d331edc654bbf1749bbd289e19f050a0df51f1c8"
metafile = true

[[files]]
file = "mods/crafting+.pw.toml"
hash = "0a7b09112a042597ed53518a14c02c45d5ff30e3a4e3ba47640b274f6dd1be15"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "9def4dc6cecd661fb14486dd2756270ae2020929324f969899c104a7c6cecb74"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "145bbc2e4170bb47c6bc40edbff1bc5b71880c4b9d4fb0393619514e468ef64f"
metafile = true

[[files]]
file = "mods/create-cobblestone.pw.toml"
hash = "cc93c7dd457427c7a6db51fe412a53771e2e6d6539d312d5141b050a32d45fb2"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "a9812ad1bbd4cf253c5c550be985ed22b177989f3b9502ac78ecd6563721b030"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "65060f66cd19ebffad8ba87a11109877fc7f6965da5e005cb14686d6f6b2cfcc"
metafile = true

[[files]]
file = "mods/create-enchantable-machinery.pw.toml"
hash = "d6e6bbfd4980ab66bce150e23e32d7468a43a6203eea5a001a1e363fb0766887"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "5735cd877c7519a2ab6c88a0508f64abd67e51b6027c728d86a4ab50e30aea7b"
metafile = true

[[files]]
file = "mods/create-goggles.pw.toml"
hash = "ff88efb77ae8899248a513bbedc17ceace77a69d789e70b47bde629761d90419"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
hash = "35d96a1eae8cf17a40846a99647927fc1170fef11f446668d7787c7161eb2220"
metafile = true

[[files]]
file = "mods/create-mechanical-spawner.pw.toml"
hash = "e28ad23aa941b216a9cd44dc5f9a5c0a1d72f9b2a86437e4db41bd073cd0e2cf"
metafile = true

[[files]]
file = "mods/create-misc-and-things.pw.toml"
hash = "2e5277e3399781103d429cde92562a6b70ad573b7cb0fa360239c6351c8a81d9"
metafile = true

[[files]]
file = "mods/create-more-automation.pw.toml"
hash = "5b0bbc0a822a704b1d22907660a7ab022e6f36c08c4866cd65fc50c747262b5b"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "a6feb15f78ee7192942287790965b40412221ac822985fdb18f05605fc951d78"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "255864fc7aa8e28619e5ddbf9094623bfcc9d6caa260bc0cd3d32b39d45a532f"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "5391ac307bbc73edb72e7eb11495af96e327eff1c02ff67d2ebbe615ca6766d7"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
hash = "d88d1845469a6f316eede279741cdedfc7489b3bef6c66405fff999e70d6c189"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "d83ee58bd994d4c13d4fc2f833e553ac55a01ced1c2e535865b1b8b50eb1362b"
metafile = true

[[files]]
file = "mods/create-tfmg.pw.toml"
hash = "d660cbfb7043a2fe367acfd546952c8b5b9ba4ee2cd02c910e5575089716994e"
metafile = true

[[files]]
file = "mods/create-utilities.pw.toml"
hash = "448ef7a4a3d83079e682a55d10e41f8ae5df430043b60dd7061d3268e72d8b35"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "efb00d657d22a7e560916ae2b7a2836f48586527a5ff40338af7e928472ef9da"
metafile = true

[[files]]
file = "mods/createaddoncompatibility.pw.toml"
hash = "abc9d37db15b923cab7bab5561e1ca7bf842d82a62ee04a1e20a4c4e9c031433"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "5cf8a06431f16a18dc468baae3fbdf17cc1d72b9697da58cb126342ed937aa59"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "d25ada163cbf92d6e8ad0532dd865e3be566a6302a190b849d3741bda318b012"
metafile = true

[[files]]
file = "mods/ctov-farmers-delight-compat.pw.toml"
hash = "ec327ba7471215f9816ab868a11a1eab1cc5361458528b06eb666677b77bb3c8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/darkrtp.pw.toml"
hash = "030d9f0383117528f0b3fe9c237626f300f53c1ef2f9473de898fa698f030d49"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "354515e4c9017acf24464556a4b56f3e15d0302308d09a9fe80817b05b6e4ff5"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "ea969a2c6d77b5e7c8bd8ab8fe52c0c46de676a9cc517f014965699d90c5ed92"
metafile = true

[[files]]
file = "mods/dynamic-village.pw.toml"
hash = "f052b01939455f3c99653719e0a30c3273617e1d49e580689adcdc09e1a755ef"
metafile = true

[[files]]
file = "mods/easy-villagers.pw.toml"
hash = "a65613e31ab6db637264a3988a390af659093d349b9a881c79222091461490d4"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "5ac6fe9a921d8fa00456ec2e18da02ede5c0da424c5c5b57da1206feeac40ff6"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "4c5ec7476521092a74d8ae1b894e44903a3d7834898674294f0ce4ddb040b251"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "cf35640e350078e8cd7b29f727c3227aeb0b465f0fba9a266e6cbe15dadc4955"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "d93c3c494955dfc44e2590ded2ee8414d582e87f2fca00575f08576ae2197d57"
metafile = true

[[files]]
file = "mods/extra-disks.pw.toml"
hash = "2f357818fc7c6da2d130182f61a693b2e3d8bf7ce171c6993795977c5f0b51d7"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/flux-networks.pw.toml"
hash = "de63df967225278681e18afe0e323110322ec02006746980fbe77dbd974b20b3"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "3a34f1ae8c1de74c432f7637cb35d901711335fe00db71c346d356e51505548a"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "c727cdfb22c0a34cafbdb2e33da7504e6aa9e96a0d78e5d913bf5fa9006d44c7"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "691798dd9acfd386bc9332249cd4c1291c646af4d97999090ec0528d9bb35c88"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "6a0155012732893dae42d8a7dae4df181367eaaea57296e0ca9849567e7b9b4f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1030e18f2e875dfdf39de82b823e1dfe6009f21f1aaad338137d3a90504e2f7e"
metafile = true

[[files]]
file = "mods/hammer-lib.pw.toml"
hash = "1a6b03437d3f80ac96348dc8e5f1077f3271f594a8a560c43375117fd8f176c1"
metafile = true

[[files]]
file = "mods/hopo-better-ruined-portals.pw.toml"
hash = "447524944a1c5ed9a90f7eabac4bcf58e8f8eaa08e349f138df664128975a8cd"
metafile = true

[[files]]
file = "mods/hopo-better-underwater-ruins.pw.toml"
hash = "f57d03cf7f86ea07a85d94ac11c15c649a7ec8db67d772845609eca42c7af7d3"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "3ca288e948a12a854c4d8e74dbf5e32302f41478b75f364709087709d66402de"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "a3ad7e869e1b5bbb07a1972325a70de2b8a1dac9e6919fd3cc1c037e77fcf4c0"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "ebdae9a6cb51722738439a66d87ba49a0e9c3ecf25e19a1834c9fcb211f79487"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b05a3744be80c41425a7b61dec7848cb66d37f33947dba0554ea234e99873af9"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "bb969935e212233b5830ba80d9dcc81479092beafefbc9ec770274990630d909"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "b29b617692233d60179a6d7376dade85063af0e73a3cc53c623bf570fb768d82"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "589b370ffcef405a00daafc5bfa6febaeafef81aa797a3cb63a49555db90fd76"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "ed461d699dfadb76e5b38cf39d1eea7c35221db5587a35bf38499782b6f98160"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "82ffc26ad624cdd846cbbeb99ed40ef44229ec7006a7ae7e8caa8df6409c20db"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "47b9410704efc0f8cb3b34a87d7019a013850775afe464e887b19ecf45eac0d3"
metafile = true

[[files]]
file = "mods/mafglib.pw.toml"
hash = "d921175a82cf60e7ebaa7f014f924b77a2f5ace44e81b309dc996c4c55b7455b"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "38eb04b5ae4e429509e8c90fed921719d600166d9be12fcd4f263cce3b117c8a"
metafile = true

[[files]]
file = "mods/nbc.pw.toml"
hash = "dd6425931b54d383c66ce1f5a86a80180302942ccd3ad3d5e1259002062a0018"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9a3c80bf6eee8234001d2a1602b3e123ac5706af051902e40f24abe317b86e50"
metafile = true

[[files]]
file = "mods/northstar-redux.pw.toml"
hash = "c54a8ce32a8b6477bca654e6e26ad850833b72391794b4dbb03097add371c3a6"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "071ce6bcd5614ceb07718b646f1012faf9c449eb8e56c0b740929a9efada593c"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "e63b436dba4a80db68e4c79e5d9f030096fad75fe264490403d75dee3dab72de"
metafile = true

[[files]]
file = "mods/petrolpark.pw.toml"
hash = "30186ce4202d872067951e23fdbfb831e5b41248534c9e44d68b548903310819"
metafile = true

[[files]]
file = "mods/petrols-parts.pw.toml"
hash = "f07927109b603c991c76f91e69e18dc0f4935b56bf7bb8a1026da9605052855e"
metafile = true

[[files]]
file = "mods/pretty-pipes.pw.toml"
hash = "d66dafbe365e449088597a71d181cfa0e91fd1bb61ab98c7c1daaf14e6b9b4d6"
metafile = true

[[files]]
file = "mods/randomtp.pw.toml"
hash = "f0977ca1246485e47523fb7ceaca96b3127424c3269df8f55bb81bde341cb181"
metafile = true

[[files]]
file = "mods/refined-storage-addons.pw.toml"
hash = "3e32f49f3c57643bde66e53f023e9f83541d0a7e36a131ca06355324351cb041"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "9a8bc01ac2c21bad372e5b7db21e6d6207c0e1f1d60d1481157a2131ad653a26"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
hash = "e3fb99dcf245b19c4add224893b8cd342c7b3db00c0f708fef9ca368b1a2d94b"
metafile = true

[[files]]
file = "mods/repurposed-structures-forge.pw.toml"
hash = "dfba92a2202ee1a5765f6f3627bb31cd4f570ffd8f3025bf2973b07e2d4bbfec"
metafile = true

[[files]]
file = "mods/rsinfinitybooster.pw.toml"
hash = "10826bc35553630ebba33287b93fc4f83fd3c597f53a26e7702ae70f7f698afd"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "817b4a47826bd99c69957fe07131d5704984f89fec96287cdc20c6fbe46100cf"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "57738899c3f550796ca3488d548b91ad713f7235bf8ac77245dc0f0fba3bea90"
metafile = true

[[files]]
file = "mods/simple-quarry.pw.toml"
hash = "e9e218427240f67a4dd3a436bdecc63c09663e952fe3613ecd29e41cd84fef6d"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "f49c7302f7a044aae67740fac3a7558ca2f26b3a89a69a3940d516a40e3b75b7"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "e4ec2a3489da9a8cf2b16abfbca6d62ef3dd0c6112d16d939641c16c5a796bea"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "131c818cca79586fdca0535062a63581e7c438efd108be4403ab8faea92e6368"
metafile = true

[[files]]
file = "mods/tool-trims.pw.toml"
hash = "10617ea3b7c98cc38a57220ac9cd801bbbd99a76f56973040a330690f5782333"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "dcef73437fec1a74a88df117d55f379860090b4e5dd73d0c19f7874e61cc6bd3"
metafile = true

[[files]]
file = "mods/tpa++.pw.toml"
hash = "10ce51a6805b47222d4bf19b7975354fcf1afedd14714ee84b9c67bbbe2cb294"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "785c5144198e9687c8ff0cf65313ebfb4fdf6302e35df1450f132f1ffc21cfb1"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "d6ddde622109dc5072e84fc6493c44950314594864a74495d898bcefbd3f2e8b"
metafile = true

[[files]]
file = "mods/viner.pw.toml"
hash = "15c237ad40f64e0bfd6c7abef6c2563e0c7a18447a1e5c9f060272e6edf815a2"
metafile = true

[[files]]
file = "mods/waystones-teleport-pets.pw.toml"
hash = "b73bb582ceb41035bca727eb0fd7c40c3605a59a19f1b69c076d1c1d4f75e147"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "073176bf34feab44656497b2e5ddf80eae8cf12f743f332d56ac0544bd91d8e2"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "c2e3390b5330508e73c0e0d42067dcbdb1137e73ce7ec4324288fd3b7ed2d50d"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "647dc25daba3bac1f6e93e3abedaa80d00c83812595e0cf42df5ae966058e84f"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "2b4c452b8e077743406460087ecba4a8e7b93d581308c4879dda8a35ed6e86c4"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "4353ffe53f1dcf34093430446f30629d5f23ae10839dd766ea4438806d915a78"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "4143741c21217772c5f568cef36ec16861f9895d193f5eff3c674a6032fac4f1"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "9ad77d663f0a287c2a902d71ccf7221f4ab49a29946743432e4ccb7506e86c21"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "584b719bb17c63ca4bb1432f45af46a17e1bce6307565f13b9c0298bb80f6945"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "7deb34098e5722d3b024231e937c66984e5874f653f0cfc95482f22bbc18f4d4"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "d92d38a261d5c8449b33c114ba3391567c5aca8853301928746de2386348b50b"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "eaa9678b7f6aee59266500c8d3fec01f7bce7c8fe5a0517747e9676cb0d2f1fc"
metafile = true
