name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b21f8b10239971a96ff1b8b44c2abffc6f5582535e65fee1f1d45caf3b6f1db"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
