name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe3119180eb3869a11738dc1686b5063d429c903c588a1fd65534d66ef22388"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
