name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "560ab0087fc2c6b6b3afe1c60b1e64f817e9a848f6f70265394b70fa279a7011"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
resourcepacks = "config/paxi/resourcepacks"
