name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "178125ea9b5c3b456111ee34b8fbaefac91d056d4101f77f807199c0e1a70701"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
