name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77c277ec43a7260040c2df5398e8152ad942e45696a5b4b26d15bdfb2334d4b5"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
