name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c4838aab07560aea552662281dec3bf8cc9158504d2b9d0347089d7157acf7e"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
