name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.4.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc873b281918727ec7f742bd5f87d9f6c331df73bef148ffa5e90e328abe6c7a"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
resourcepacks = "config/paxi/resourcepacks"
