name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e91fc499f48b26d87ad9654f4b5bdf412f228aa93043ba01dd2607e449526bf8"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
resourcepacks = "config/paxi/resourcepacks"
