name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42537417016f3179a0fb818d9ecfd21b8ab5a58618bf833ace3a8d673b0466da"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
