name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a6fe9f910ccddbc42e7baed2e1a65db3ffcb4a4a051e75f15ed3b57df2d4c19"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
resourcepacks = "config/paxi/resourcepacks"
