name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "448f4771996144c2c5f8ca4bcd28aa2b2c66ceaa3e4c5bdc4828871bfbe61f31"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
