name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21ad676aa71d153d1fa377839c11aacfd073b0d8e0532d0aef0f33fb146eb48f"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
