name = "Rapid's Create & Miscellaneous ModPack"
author = "RapidFuge"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bfbb0a1bad15fafb3923c10772a585c778cf97851cf11bf51b8a49c80cf61e7"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
